import '@/app/globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/header'
import '@/app/globals.css'
// otros imports




const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ORM Prisma',
  description: 'Generated by create next app',
  manifest: '/manifest.webmanifest'
}

export default async function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={inter.className} style={{backgroundImage: "url('fondo1.jpg')"}}>
        <Header/>
        {children}
      </body>
    </html>
  )
}
